In [1]:
import numpy 
import numpy as np

# Objets de type array

Les objets de type array correspondent à des tableaux à une ou plusieurs dimensions et permettent d’effectuer du
calcul vectoriel. La fonction array() convertit un conteneur (comme une liste ou un tuple) en un objet de type array.

## Fonction array

In [3]:
import numpy as np
a = [1, 2, 3]
ta = np.array(a)

In [6]:
type(ta)

numpy.ndarray

Un objet array ne contient que des données homogènes, c’est-à-dire d’un type identique.
Il est possible de créer un objet array à partir d’une liste constituée d’entiers et de floats, mais toutes les
valeurs seront alors comprises par NumPy comme des floats

In [11]:
import numpy as np
a = [1, 2.2, 3, 'bonjour']
ta = np.array(a)

ta

array(['1', '2.2', '3', 'bonjour'], dtype='<U32')

In [13]:
import numpy as np
a = [1, 2.2, 3]
ta = np.array(a)

ta

array([1. , 2.2, 3. ])

In [14]:
ta.dtype

dtype('float64')

In [15]:
import numpy as np
a = [1, 2, 3]
ta = np.array(a)

ta.dtype

dtype('int64')

In [19]:
np.array([3])**456

array([924717970289206433])

## Fonction arange



In [23]:
np.arange(100000000-1, 0, -1)

array([99999999, 99999998, 99999997, ...,        3,        2,        1])

## Différence avec les listes ou tuple
La différence fondamentale entre un objet array à une dimension et une liste (ou un tuple) est que celui-ci est
considéré comme un vecteur. Par conséquent, on peut effectuer des opérations vectorielles élément par élément sur ce type d’objet, ce qui est bien commode lorsqu’on analyse de grandes quantités de données

* opérations mathématiques
* fonctions mathématiques

In [31]:
a = [1, 2, 3]
ta = np.array(a)

b = [4, 20, 13]
tb = np.array(b)

ta ** tb

array([      1, 1048576, 1594323])

In [33]:
np.sin(ta)

array([0.84147098, 0.90929743, 0.14112001])

In [34]:
import math

math.sin(ta)

TypeError: only length-1 arrays can be converted to Python scalars

In [37]:
ta[0] = 14.8
ta

array([14,  2,  3])

## Méthodes sur les tableaux

In [39]:
b = [4, 20, 13]
tb = np.array(b)

np.min(tb)
tb.min()

4

In [41]:
tb.mean()
tb.std()
tb.var()

42.88888888888889

In [42]:
tb.sum()
tb.prod()

1040

In [43]:
tb.sort()
tb

array([ 4, 13, 20])

In [44]:
b = [4, 20, 13]
tb = np.array(b)

tb.argsort()

array([0, 2, 1])

## Indices

In [45]:
b = [4, 20, 13, 45, 2, 6, 86, 2]
tb = np.array(b)

tb

array([ 4, 20, 13, 45,  2,  6, 86,  2])

In [46]:
tb[5]

6

In [47]:
tb[1:4]

array([20, 13, 45])

In [48]:
indices = np.array([4, 2, 3])
tb[indices]

array([ 2, 13, 45])

In [49]:
b = [4, 20, 13, 45]
tb = np.array(b)

tb

array([ 4, 20, 13, 45])

In [50]:
masque = np.array([False, True, False, True])

tb[masque]

array([20, 45])

In [51]:
(tb>10)

array([False,  True,  True,  True])

In [55]:
tb[tb>10]

array([20, 13, 45])

In [57]:
tb != 13

array([ True,  True, False,  True])

In [59]:
tb[tb+10]

IndexError: index 14 is out of bounds for axis 0 with size 4

In [58]:
tb+10

array([14, 30, 23, 55])

## Fonctions avec des tableaux

## Concaténation d’arrays

In [32]:
np.concatenate((ta, tb))

array([ 1,  2,  3,  4, 20, 13])

# Tableaux multidimensionels

* Array et dimensions
* Méthodes de calcul sur les arrays et l’argument axis
* zéros, ones, full

## Chargement d’un array depuis un fichier

# Masques booléens

# Exercices

## Jour le plus chaud

Le fichier temperature.dat (https://python.sdv.u-paris.fr/data-files/temperatures.dat) contient un relevé de quatre températures pour chaque jour de la semaine

À l’aide du module NumPy, on souhaite déterminer quel est le jour de la semaine le plus chaud. Pour cela nous vous proposons les étapes suivantes :
1. Récupérez le nom des jours de la semaine depuis le fichier et stockez-les dans une liste days.
2. Récupérez les valeurs de températures depuis le fichier et stockez-les dans un array 2D. La fonction np.loadtxt et son argument usecols vous seront utiles.
3. Parcourez chaque ligne de la matrice, calculez la température moyenne de chaque jour puis stockez-la dans une liste mean_temps.
4. À l’aide des deux listes days et mean_temps, déterminez et affichez le jour le plus chaud.




## Calcul Monte-Carlo de la surface d’un disque

La fonction np.random.rand permet de créer une distribution uniforme de points entre 0 et 1.

* Créer deux tableaux X et Y de de N variables uniforméments réparties entre -1 et 1. Pour cela on utilisera le fait que si a est entre 0 et 1, alors $2a - 1$ est entre -1 et 1.

* Créer un tableau R contenant la longueur de chaque rayon.

* Créer un tableau de booléen indiquant les points dans un cercle de rayon 1. 

* Pour calculer le nombre de valeur vraie d'un tableau de booléens, on peut utiliser la fonction sum qui va remplacer les False par 0 et les True par 1. Calculer la proportion de points dans le cercle.

* Estimer une valeur de pi à partir de l'estimation de la probabilité d'être dans le cercle en prenant N grand.

* De la même façon, évaluer le volume d’une sphère en dimension 13

In [60]:
np.random.rand(10)

array([0.300532  , 0.33887762, 0.13480932, 0.68946887, 0.57944208,
       0.64672863, 0.38340429, 0.25091658, 0.39898426, 0.86293429])

## Calcul de la moyenne

Un tableau numpy contient les notes d’une classe. Chaque ligne correspond à un élève et chaque colone à un examen.

In [3]:
import numpy as np

N_eleves = 35
N_examens = 3

notes = np.random.rand(N_eleves, N_examens)*20

* Calculer la moyenne de chaque élève. Calculer la moyenne pour chaque examen.
* Calculer la moyenne de chaque élève, sachant que les coeficients pour les 3 examens sont de 1, 3 et 2.